# Generated by Django 4.2.14 on 2024-08-05 10:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('brewery', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=50)),
                ('abv', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
    ]
