# Generated by Django 4.2.14 on 2024-08-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default='Review Title', max_length=50),
        ),
    ]
