# Generated by Django 4.2.14 on 2024-08-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
