# Generated by Django 4.2.14 on 2024-08-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_card', '0002_alter_beer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='content',
            field=models.TextField(),
        ),
    ]
