# Generated by Django 4.2.14 on 2024-08-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_card', '0002_review_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(max_length=50),
        ),
    ]
